// BushSweeper 1.0
// License : GPL
// Programmed by BlueKid
// http://derindelimavi.blogspot.com/
// Sent me any suggestion, modification or bugs. Don't hesitate to contact
// me for any question, I will be very grateful with your feedbacks.
// bluekid70@gmail.com
// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef BushSwp_h
#define BushSwp_h
#include <FL/Fl.H>
#include <FL/fl_ask.H>
#include <stdio.h>
#include <stdlib.h>
#include "Cell.h"
#include "board.h"
#include "Animated_Icon.h"
extern short *cells; 
extern Board *brd; 
extern char AIconPath[1024]; 
extern char Buf1[50],Buf2[50],Buf3[50],Buf4[50]; 
extern int x_limit, y_limit,nBush,level,iBush; 
extern int nCells,nSigned,MaxTime; 
extern bool Playing,TimeL; 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Progress.H>
extern Fl_Progress *KHucre;
extern void Map_CB(GMap*, void*);
extern GMap *Map;
#include <FL/Fl_Button.H>
extern Fl_Progress *RTime;
Fl_Double_Window* make_window();
void NewGame();
void OpenCells();
void Map_CB(GMap*, void*bt);
void OpenVoids(int x, int y);
#include <FL/Fl_Return_Button.H>
extern void cb_Ok(Fl_Return_Button*, void*);
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>

class Loose {
public:
  Loose();
  Fl_Double_Window *window;
  Fl_Return_Button *Ok;
  Animated_Icon *Icon1;
  void show();
  void hide();
};

class Start {
public:
  Start();
  Fl_Double_Window *window;
  Fl_Return_Button *Ok;
private:
  void cb_Ok_i(Fl_Return_Button*, void*);
  static void cb_Ok(Fl_Return_Button*, void*);
public:
  Fl_Box *Level;
  Fl_Box *nBsh;
  void show();
  void hide();
};
void cb_Ok(Fl_Return_Button*o, void*w);

class Win {
public:
  Win();
  Fl_Double_Window *window;
  Fl_Return_Button *Ok;
  void show();
  void hide();
};

class About {
public:
  About();
  Fl_Double_Window *window;
  Fl_Return_Button *Ok;
  void show();
  void hide();
};
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Check_Button.H>

class Options {
public:
  Options();
  Fl_Double_Window *window;
  Fl_Return_Button *Ok;
private:
  void cb_Ok1_i(Fl_Return_Button*, void*);
  static void cb_Ok1(Fl_Return_Button*, void*);
public:
  Fl_Value_Slider *OptionnBush;
  Fl_Check_Button *TimeLimit;
private:
  void cb_TimeLimit_i(Fl_Check_Button*, void*);
  static void cb_TimeLimit(Fl_Check_Button*, void*);
public:
  Fl_Value_Slider *Time;
  void show();
  void hide();
};
void Timer(void*);
void SetLabel();
#endif
